PUT {{url}}/user/600be461d9eda464bd39695c
Content-Type: application/json
Authorization: {{token}}

{
    "role": "600b99b27ecd7c546ac957ec"
}

###
GET {{url}}/user/600bdb44e7b1b65ebcada6a1/info
Accept: application/json
Authorization: {{token}}

###
GET {{url}}/user/mine
Accept: application/json
Authorization: {{token}}

###
GET {{url}}/user/list?offset=0&limit=10
Accept: application/json
Authorization: {{token}}

###
POST {{url}}/user/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "123456"
}

###

POST {{url}}/user/create
Content-Type: application/json

{
    "username": "admin2",
    "password": "123456",
    "role": "600b87b61dd7d3508877b71a"
}

